name: Publish Crate

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Check version consistency
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          CRATE_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')
          if [ "$TAG_VERSION" != "$CRATE_VERSION" ]; then
            echo "Tag version (v$TAG_VERSION) does not match Cargo.toml version ($CRATE_VERSION)"
            exit 1
          fi

      - name: Publish to crates.io
        run: cargo publish --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
